from rsf.proj import *

#--Lectura de datos SGY--#
##--Sismica en profundidad (PSDM)
seis_data_z = 'subvolumen_amp_sg_chocol_depth_h61055.sgy'
Flow('input_z', seis_data_z, 
	'''
	segyread hfile=hfile bfile=bfile tfile=tfile.rsf 
	''')

Flow('cubo_z', 'input_z', 
	'''
	intbin inv=n head=tfile.rsf xk=xline yk=iline | 
	put label1=Profundidad unit1=km label3=inline label2=xline 
	''')

Flow('seccion_z', 'cubo_z', 'window  n3=1 f3=350')

Result('seccion_z', 
	'''
	window min2=1810 | 
	grey title="PSDM" labelsz=6 titlesz=6
	''')

##--Velocidades de intervalo (PSDM)
seis_data_v = 'subvolumen_vel_chocol_depth_h61055.sgy'
Flow('input_v', seis_data_v, 
	'''
	segyread hfile=hfile1 bfile=bfile1 tfile=tfile1.rsf
	''')

Flow('cubo_v', 'input_v', 
	'''
	intbin inv=n head=tfile1.rsf xk=xline yk=iline | scale dscale=0.001 |
	put label1=Profundidad unit1=km label3=inline label2=xline 
	''')

Flow('seccion_v', 'cubo_v', 'window  n3=1 f3=350')

Result('seccion_v ', 
	'''
	window min2=1810 |
	grey allpos=y scalebar=y barreverse=y 
	title="Velocidad PSDM" color=j label1=Profundidad unit1=km label2=xline
	labelsz=6 titlesz=6
	''')

#--> velocidad PSDM suavizada <--minval=1.5 maxval=5.5
Flow('smooth_v' , 'seccion_v', 'smooth rect1=250 rect2=50 ')

Result(' smooth_v ',
	'''
	window min2=1810 |
	grey allpos=y scalebar=y barreverse=y 
	title="Velocidad PSDM filtrada" color=j
	label1=Profundidad unit1=km label2=xline labelsz=6 titlesz=6
	''')

##---Convertir velocidad de intervalo PSDM (en profundidad) a velocidad de Dix (en tiempo)
#

Flow('v_dixt','seccion_v',
     ''' 
	transp | ve2d nt=1250 dt=0.004  | put label2=Tiempo unit2=s
     ''')

Result('v_dixt',
	''' 
	transp  | window min2=1810 | 
	grey allpos=y scalebar=y barreverse=y minval=1.5 maxval=5.5
	title="Velocidad Dix" color=j label1=Tiempo unit1=s label2=xline barunit=km/s 
	labelsz=6 titlesz=6
     	''')

Flow('v_dixt1','smooth_v',
     ''' 
	transp | ve2d nt=1250 dt=0.004 | put label2=Tiempo unit2=s
     ''')

Result('v_dixt1 ',
	''' 
	transp | window min2=1810 |
	grey allpos=y scalebar=y barreverse=y minval=1.5 maxval=5.5
	title="Velocidad Dix" color=j label1=Tiempo unit1=s label2=xline barunit=km/s 
	labelsz=6 titlesz=6
     	''')

###----Convertir velocidad de Dix (en tiempo) a profundidad para comparar velocidades en el mismo dominio
#..........(window min2=1845 porque aparecen 5 trazas con valores de 0 km/s)
#Flow('v_dixz', 'v_dixt',
#	''' time2depth velocity=$SOURCE nz=1601 dz=0.005 intime=y  | 
#	put label1=Profundidad unit1=km 
#	''')

#Result('v_dixz ', 
#	'''
# 	 grey allpos=y bias=1.9  scalebar=y barreverse=y 
#	title="Velocidad Dix: Tiempo -> Prof" color=j label1=Profundidad unit1=km 
#	label2=xline barunit=km/s 
#	''')

#Flow('v_dixz1', 'v_dixt1',
#	''' time2depth velocity=$SOURCE nz=1601 dz=0.005 intime=y  | 
#	put label1=Profundidad unit1=km 
#	''')


#Result('v_dixz1 ', 
#	'''
# 	 grey allpos=y bias=1.9 scalebar=y barreverse=y 
#	title="Velocidad Dix: Tiempo -> Prof" color=j label1=Profundidad unit1=km 
#	label2=xline barunit=km/s 
#	''')

#Result('psdm_dixt1', ' seccion_v v_dixt1 ', 'SideBySideIso')
#Result('dix_orig_smooth', 'v_dixt v_dixt1 ', 'SideBySideIso')


##----El programa cameron2d convierte la velocidad de Dix a velocidad de intervalo mediante el metodo de Chebyshev 
#......... (a partir del modelo de velocidad PSDM original)
#  , 

Flow('v_cam x0 t0', 'v_dixt',
	''' 
	cameron2d method=cheb nz=1601 dz=0.005 neval=20 nc=1000 x0=${TARGETS[1]} t0=${TARGETS[2]} | 
	put label2=Profundidad unit2=km 
	''' )
Result('v_cam',  
        '''
	transp | window min2=1810 |
	grey allpos=y scalebar=y barreverse=y minval=1.5 maxval=5.5
	title="Velocidad Estimada" color=j label1=Profundidad unit1=km label2=xline
	labelsz=6 titlesz=6
	''')

Flow('v_cam1 x1 t1', 'v_dixt1',
	''' 
	cameron2d method=cheb nz=1601 dz=0.005 neval=10 nc=1000 x0=${TARGETS[1]} t0=${TARGETS[2]} | 
	put label2=Profundidad unit2=km
	''' )
Result('v_cam1',  
        '''
	transp | window min2=1810 |
	grey allpos=y scalebar=y barreverse=y minval=1.5 maxval=5.5
	title="Velocidad Estimada" color=j label1=Profundidad unit1=km label2=xline
	labelsz=6 titlesz=6
	''')

#Result('psdm_dix_cam', ' seccion_v v_dixt v_cam ', 'SideBySideIso')
#Result('psdm_dix_cam1', ' seccion_v v_dixt1 v_cam1 ', 'SideBySideIso')

# Map PSTM to depth

#Flow('coord','t0 x0',
#     '''
#     scale dscale=2 | cat axis=3 ${SOURCES[1]} | transp plane=13 
#     ''')

#Flow('seccion_t_conv','seccion_z coord',
#     '''
#     pad beg2=150 end2=150 | put o2=1804 |
#     inttest2 interp=spline nw=4 coord=${SOURCES[1]} 
#     window n2=391 f2=151
#     ''')

Flow('v_cam_trans','v_cam','transp')
Flow('seccion_t_conv2','seccion_z seccion_v',
	'''
	depth2time velocity=${SOURCES[1]} nt=1205 dt=0.004
	''')

Result('seccion_t_conv2',
     '''
     window min2=1810 | grey title="PSDM Prof -> Tiempo"
     label1=Tiempo unit1=s label2=XLine 
     labelsz=6 titlesz=6 
     ''')

Flow('v_cam_trans1','v_cam1','transp')
Flow('seccion_t_conv1','seccion_z v_cam_trans1',
	'''
	depth2time velocity=${SOURCES[1]} nt=1205 dt=0.004
	''')

Result('seccion_t_conv1',
     '''
     window min2=1810 | grey title="PSDM Prof -> Tiempo (smooth)"
     label1=Tiempo unit1=s label2=XLine 
     labelsz=6 titlesz=6 
     ''')

#Result('sism_conv_tiempo','seccion_z seccion_t_conv seccion_t_conv1','SideBySideIso')

End()

